language: node_js
sudo: false

node_js:
  - "4"
  - "6"

services:
  - postgresql

before_script:
  - psql -c 'create database versiondb;' -U postgres

env:
  - DATABASE_URL="postgres://postgres@localhost/versiondb"
